"""add recurring calendar events

Revision ID: 05573d91172d
Revises: 2f737ea67a07
Create Date: 2026-09-17 09:22:05.427387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05573d91172d'
down_revision: Union[str, None] = '2f737ea67a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_frequency', sa.Enum('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', name='recurrencefrequency'), nullable=True))
        batch_op.add_column(sa.Column('recurrence_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_calendar_events_recurrence_group_id', 'calendar_events', ['recurrence_group_id'], ['id'], use_alter=True)
        batch_op.drop_column('recurrence_rule')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_rule', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_constraint('fk_calendar_events_recurrence_group_id', type_='foreignkey')
        batch_op.drop_column('recurrence_group_id')
        batch_op.drop_column('recurrence_end_date')
        batch_op.drop_column('recurrence_frequency')

    # ### end Alembic commands ###
