"""add all_teams flag to milestones

Revision ID: 3a7a6f4aacfc
Revises: a273bd8dc6c7
Create Date: 2026-09-09 00:00:21.199750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7a6f4aacfc'
down_revision: Union[str, None] = 'a273bd8dc6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('all_teams', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_column('all_teams')

    # ### end Alembic commands ###
