"""comment status_change columns as plain strings

Revision ID: 7d364c4b6967
Revises: 54f223beab74
Create Date: 2026-09-04 11:02:22.053543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d364c4b6967'
down_revision: Union[str, None] = '54f223beab74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('status_change_from',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.alter_column('status_change_to',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('status_change_to',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
        batch_op.alter_column('status_change_from',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###
