"""add all_teams flag to activities and calendar_events

Revision ID: a273bd8dc6c7
Revises: 10a3e3b0da62
Create Date: 2026-09-08 19:48:36.553843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a273bd8dc6c7'
down_revision: Union[str, None] = '10a3e3b0da62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('all_teams', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('all_teams', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('all_teams')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('all_teams')

    # ### end Alembic commands ###
